-- =============================================
-- POSTGRESQL SCHEMA FOR E-SIGNATURE SYSTEM
-- Bao gồm module: Core, Document, Audit, WebAuthn/FIDO2
-- =============================================

-- Xóa schema cũ nếu cần thiết (Cẩn thận khi chạy trên production)
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- 1. ĐỊNH NGHĨA CÁC ENUM TYPES (Chuẩn hóa dữ liệu)
CREATE TYPE user_role_type AS ENUM ('ADMIN', 'MEMBER');
CREATE TYPE account_type_enum AS ENUM ('PERSONAL', 'ORGANIZATION');
CREATE TYPE plan_type_enum AS ENUM ('personal', 'organization');
CREATE TYPE signature_type_enum AS ENUM ('drawn', 'uploaded', 'typed');
CREATE TYPE doc_status_enum AS ENUM ('draft', 'pending', 'completed', 'declined');
CREATE TYPE version_type_enum AS ENUM ('uploaded', 'prepared', 'signed');
CREATE TYPE signer_role_enum AS ENUM ('signer', 'viewer');
CREATE TYPE signing_mode_enum AS ENUM ('sequential', 'parallel');
CREATE TYPE signer_status_enum AS ENUM ('waiting', 'viewed', 'signed', 'declined');
CREATE TYPE session_status_enum AS ENUM ('active', 'used', 'expired', 'revoked');
CREATE TYPE field_type_enum AS ENUM ('signature', 'text', 'checkbox', 'date');
CREATE TYPE audit_event_enum AS ENUM ('created', 'email_sent', 'viewed', 'token_verified', 'otp_requested', 'otp_verified', 'signed', 'declined', 'completed');
CREATE TYPE payment_method_enum AS ENUM ('credit_card', 'bank_transfer', 'paypal');
CREATE TYPE payment_status_enum AS ENUM ('pending', 'completed', 'failed');
CREATE TYPE signature_format_enum AS ENUM ('webauthn', 'pkcs1', 'pkcs7', 'raw'); -- Mới cho WebAuthn

-- 2. USERS (Định danh người dùng)
CREATE TABLE USERS (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);
CREATE INDEX idx_users_email ON USERS(email);

-- 3. SERVICE_PLANS (Gói dịch vụ)
CREATE TABLE SERVICE_PLANS (
    service_plan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL,
    plan_type plan_type_enum NOT NULL,
    description TEXT,
    price DECIMAL(10,2) DEFAULT 0.00,
    max_users INT DEFAULT 1,
    max_documents_per_month INT DEFAULT 100,
    api_access BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. ACCOUNTS (Không gian làm việc)
CREATE TABLE ACCOUNTS (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    account_name VARCHAR(255) NOT NULL,
    account_type account_type_enum NOT NULL,
    service_plan_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (service_plan_id) REFERENCES SERVICE_PLANS(service_plan_id)
);

-- 5. ACCOUNT_MEMBERS (Quản lý thành viên)
CREATE TABLE ACCOUNT_MEMBERS (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role user_role_type NOT NULL DEFAULT 'MEMBER',
    can_upload BOOLEAN DEFAULT FALSE,
    can_sign BOOLEAN DEFAULT FALSE,
    can_view_docs BOOLEAN DEFAULT FALSE,
    can_invite BOOLEAN DEFAULT FALSE,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (account_id, user_id),
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- 6. USERS_KEYS (MỚI: Quản lý khóa WebAuthn/FIDO2)
CREATE TABLE USERS_KEYS (
    key_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    credential_id VARCHAR(255) UNIQUE NOT NULL,    -- ID credential từ WebAuthn
    public_key_pem TEXT NOT NULL,                  -- Public key
    algorithm VARCHAR(50) NOT NULL,                -- Ed25519/ECDSA_P256...
    aaguid VARCHAR(64),                            -- Authenticator Attestation GUID
    attestation_format VARCHAR(50),
    attestation_trust_path JSONB,                  -- Lưu chuỗi chứng chỉ
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX idx_user_keys_user ON USERS_KEYS(user_id);

-- POSTGRES EXCLUSIVE: Partial Index để đảm bảo mỗi user chỉ có 1 khóa active

CREATE UNIQUE INDEX uk_user_active_key ON USERS_KEYS(user_id) WHERE is_active = TRUE;   

-- 7. SIGNATURES (Mẫu chữ ký hiển thị - Hình ảnh)
CREATE TABLE SIGNATURES (
    signature_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    signature_type signature_type_enum NOT NULL,
    image_url VARCHAR(255),
    image_hash VARCHAR(255),
    text_style VARCHAR(100),
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);
CREATE INDEX idx_signatures_user ON SIGNATURES(user_id);

-- 8. DOCUMENTS
CREATE TABLE DOCUMENTS (
    document_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    title VARCHAR(200),
    description TEXT,
    original_file_url VARCHAR(255) NOT NULL,
    original_file_hash VARCHAR(255),
    final_file_url VARCHAR(255),
    final_file_hash VARCHAR(255),
    status doc_status_enum DEFAULT 'draft',
    expiration_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id),
    FOREIGN KEY (uploaded_by) REFERENCES USERS(user_id)
);
CREATE INDEX idx_documents_account ON DOCUMENTS(account_id);

-- 9. DOCUMENT_VERSIONS
CREATE TABLE DOCUMENT_VERSIONS (
    version_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INT NOT NULL,
    file_url VARCHAR(255) NOT NULL,
    version_type version_type_enum NOT NULL,
    version_number INT DEFAULT 1,
    hash_value VARCHAR(255) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (document_id, version_number),
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id),
    FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);

-- 10. DOCUMENT_TEMPLATES
CREATE TABLE DOCUMENT_TEMPLATES (
    template_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    file_url VARCHAR(255) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id),
    FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);

-- 11. DOCUMENT_SIGNERS (Cập nhật WebAuthn)
CREATE TABLE DOCUMENT_SIGNERS (
    doc_signer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INT NOT NULL,
    user_id BIGINT,
    signer_email VARCHAR(150) NOT NULL,
    signer_name VARCHAR(200),
    role signer_role_enum DEFAULT 'signer',
    signing_order INT DEFAULT 1,
    signing_mode signing_mode_enum DEFAULT 'parallel',
    status signer_status_enum DEFAULT 'waiting',
    signed_at TIMESTAMP,
    ip_address VARCHAR(45),
    
    -- Visual Signature
    signature_image_url VARCHAR(255),
    signature_hash VARCHAR(255),
    
    -- Digital Signature / WebAuthn Fields (MỚI)
    credential_id VARCHAR(255),                  -- Khóa nào đã dùng để ký
    key_algorithm VARCHAR(50),
    message_to_sign_hash VARCHAR(255),           -- Hash của nội dung gốc cần ký
    digital_signature TEXT,                      -- Chữ ký số base64
    digital_signature_hash VARCHAR(255),
    signature_format signature_format_enum DEFAULT 'webauthn',
    
    device_fingerprint VARCHAR(512),
    email_sent_at TIMESTAMP,
    email_opened_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id),
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
    -- Constraint logic kiểm tra credential thuộc về user sẽ được xử lý ở tầng Application 
    -- hoặc Trigger phức tạp nếu cần thiết.
);
CREATE INDEX idx_doc_signers_doc ON DOCUMENT_SIGNERS(document_id);
CREATE INDEX idx_doc_signers_email ON DOCUMENT_SIGNERS(signer_email);

-- 12. SIGNING_SESSIONS (Cập nhật WebAuthn)
CREATE TABLE SIGNING_SESSIONS (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_signer_id INT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    
    -- WebAuthn Challenge Fields (MỚI)
    challenge VARCHAR(255) NOT NULL,      -- Nonce từ server
    rp_id VARCHAR(255),                   -- Domain
    origin VARCHAR(255),                  -- Origin
    assertion_verified BOOLEAN DEFAULT FALSE,
    
    status session_status_enum DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    used_at TIMESTAMP,
    used_from_ip VARCHAR(45),
    used_from_ua TEXT,
    device_fingerprint VARCHAR(512),
    otp_required BOOLEAN DEFAULT FALSE,
    otp_verified BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (doc_signer_id) REFERENCES DOCUMENT_SIGNERS(doc_signer_id)
);
CREATE INDEX idx_signing_sessions_token ON SIGNING_SESSIONS(token_hash);

-- 13. SIGNATURE_FIELDS
CREATE TABLE SIGNATURE_FIELDS (
    field_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INT NOT NULL,
    user_id BIGINT,
    page_number INT NOT NULL,
    pos_x FLOAT,
    pos_y FLOAT,
    width FLOAT,
    height FLOAT,
    field_type field_type_enum DEFAULT 'signature',
    value TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id),
    FOREIGN KEY (user_id) REFERENCES USERS(user_id)
);

-- 14. OTP_CHALLENGES
CREATE TABLE OTP_CHALLENGES (
    otp_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signing_session_id INT NOT NULL,
    otp_hash VARCHAR(255) NOT NULL,
    attempts INT DEFAULT 0,
    expires_at TIMESTAMP,
    verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (signing_session_id) REFERENCES SIGNING_SESSIONS(session_id)
);

-- 15. ACTIVITY_LOGS
CREATE TABLE ACTIVITY_LOGS (
    log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    document_id INT,
    action VARCHAR(100),
    description TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    user_agent TEXT,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id),
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id)
);

-- 16. AUDIT_TRAIL (Bằng chứng pháp lý - Cập nhật WebAuthn)
CREATE TABLE AUDIT_TRAIL (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id INT NOT NULL,
    event_type audit_event_enum NOT NULL,
    event_description TEXT,
    signer_email VARCHAR(150),
    signer_name VARCHAR(200),
    signer_ip VARCHAR(45),
    device_fingerprint VARCHAR(512),
    
    -- Integrity Data
    pdf_hash_before VARCHAR(255),
    pdf_hash_after VARCHAR(255),
    
    -- WebAuthn Audit Data (MỚI)
    credential_id VARCHAR(255),
    digital_signature TEXT,
    digital_signature_hash VARCHAR(255),
    message_to_sign_hash VARCHAR(255),
    key_algorithm VARCHAR(50),
    
    event_data JSONB, -- Dùng JSONB cho Postgres
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id),
    FOREIGN KEY (created_by) REFERENCES USERS(user_id)
);
CREATE INDEX idx_audit_doc ON AUDIT_TRAIL(document_id);

-- 17. AUDIT_CHAIN (Blockchain nội bộ)
CREATE TABLE AUDIT_CHAIN (
    chain_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL,
    prev_hash VARCHAR(255),
    entry_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (audit_id) REFERENCES AUDIT_TRAIL(audit_id)
);

-- 18. SIGNATURE_PREPARES (MỚI: Lưu thông điệp chuẩn hóa để ký)
-- Bảng này giúp tách biệt quá trình Hash message và quá trình Ký
CREATE TABLE SIGNATURE_PREPARES (
    prepare_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signing_session_id INT NOT NULL,
    document_id INT NOT NULL,
    doc_signer_id INT NOT NULL,
    message_to_sign TEXT NOT NULL,         -- JSON canonicalized hoặc String
    message_to_sign_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (signing_session_id) REFERENCES SIGNING_SESSIONS(session_id),
    FOREIGN KEY (document_id) REFERENCES DOCUMENTS(document_id),
    FOREIGN KEY (doc_signer_id) REFERENCES DOCUMENT_SIGNERS(doc_signer_id),
    UNIQUE (signing_session_id)
);

-- 19. PAYMENTS
CREATE TABLE PAYMENTS (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    service_plan_id INT NOT NULL,
    amount DECIMAL(10,2),
    payment_method payment_method_enum NOT NULL,
    payment_status payment_status_enum DEFAULT 'pending',
    provider_response JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id),
    FOREIGN KEY (service_plan_id) REFERENCES SERVICE_PLANS(service_plan_id)
);

-- 20. API_KEYS
CREATE TABLE API_KEYS (
    api_key_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT FALSE,
    restrictions JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES ACCOUNTS(account_id)
);

-- =============================================
-- TRIGGERS CHO IMMUTABILITY (APPEND-ONLY)
-- Trong Postgres, dùng Function + Trigger
-- =============================================

-- Hàm chặn UPDATE/DELETE
CREATE OR REPLACE FUNCTION prevent_modification()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'This table is append-only. Modification is not allowed.';
END;
$$ LANGUAGE plpgsql;

-- Áp dụng cho AUDIT_TRAIL
CREATE TRIGGER trg_audit_prevent_update
BEFORE UPDATE ON AUDIT_TRAIL
FOR EACH ROW EXECUTE FUNCTION prevent_modification();

CREATE TRIGGER trg_audit_prevent_delete
BEFORE DELETE ON AUDIT_TRAIL
FOR EACH ROW EXECUTE FUNCTION prevent_modification();

-- Áp dụng cho AUDIT_CHAIN
CREATE TRIGGER trg_auditchain_prevent_update
BEFORE UPDATE ON AUDIT_CHAIN
FOR EACH ROW EXECUTE FUNCTION prevent_modification();

CREATE TRIGGER trg_auditchain_prevent_delete
BEFORE DELETE ON AUDIT_CHAIN
FOR EACH ROW EXECUTE FUNCTION prevent_modification();



// Parse response
            // We assume request.getCredentialJson() is the JSON result from
            // JSON.stringify(credential) on client
            // But wait, standard JSON.stringify on PublicKeyCredential doesn't work well
            // with ArrayBuffers.
            // Client usually sends: id, rawId, response: { attestationObject,
            // clientDataJSON } (base64url encoded usually)

            // For now, let's assume usage of Github's webauthn-json library or similar on
            // frontend which handles this.
            // Or manual parsing.

            // Actually, WebAuthn4J expects RegistrationRequest object
            // I'll need to map the incoming JSON to RegistrationRequest manually or via
            // DTO.
            // Let's rely on standard parsing if possible.

            // Simpler: Let's assume the input is just the raw fields we need, or parse the
            // JSON string.
            // I will use WebAuthn4J's parser if available for JSON.
            // BUT, `RegistrationRequest` constructor takes byte arrays.

            // I'll assume the client sends a JSON structure that I can deserialize into a
            // helper DTO
            // Then convert to RegistrationRequest

            // NOTE: Implementing robust finishRegistration requires careful handling of the
            // input format.
            // I will create a method to parse the JSON and extract:
            // clientDataJSON (byte[]), attestationObject (byte[]), clientExtensions
            // (optional)

            // Let's look at `request.getCredentialJson()`.
            // Ideally, I should verify the signature.

            // Since this is complex, I will provide a placeholder logic that:
            // 1. Parses the JSON
            // 2. Extracts clientDataJSON and attestationObject
            // 3. Calls webAuthnManager.validate()

            // ... Skipping detailed JSON parsing code for brevity, will imply standard
            // structure ...

            // For the sake of this task, I will mock the validation or try to implement it
            // simply if I can guess the format.
            // Standard format from `github/webauthn-json` is Base64URL strings.

            // I'll implement a 'best effort' finish using ObjectConverter if possible.

            // Actually, to correctly support this I need the Frontend to use `base64url`
            // encoding for buffers.

            // Let's write the validation logic assuming we can parse it.

            // Construct RegistrationRequest (this is hypothetical, depends on DTO)
            // RegistrationRequest registrationRequest = new
            // RegistrationRequest(attestationObject, clientDataJSON);
            // RegistrationParameters registrationParameters = new
            // RegistrationParameters(serverProperty, challenge, false);
            // RegistrationData registrationData =
            // webAuthnManager.parse(registrationRequest);
            // webAuthnManager.validate(registrationData, registrationParameters);

            // Then save credential.

            // Due to complexity, I'll put a placeholder `save` here and notify user I need
            // the libraries for JSON parsing or specific DTO structure.
            // BUT user asked to "Implement".
            // I will try to implement a robust parser using Jackson and custom DTOs if
            // needed.

            // Let's implement a simple parser assuming standard structure.