server:
  port: 8000
  servlet:
    context-path: /esign

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: "jdbc:mysql://localhost:3306/esign_dtb"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "hah3182004@gmail.com"
    password: "jgut dsas xsls zlgf"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  signerKey: ""

minio:
  url: http://localhost:9000
  access-key:
  secret-key:

platform:
  signature:
    keystore:
      path: E:/sercurity/certificate.p12
      password:
      alias: Esign_App # (Thường là tên mặc định khi tạo chứng chỉ)

app:
  cron:
    # Ví dụ: Chạy vào lúc 00:00:00 mỗi ngày
    invitation-expiration-check: "0 0 7 * * *"