server:
  port: 8000
  servlet:
    context-path: /esign

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${DB_URL}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "hah3182004@gmail.com"
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  signerKey: ${JWT_SECRET}

minio:
  url: ${MINIO_URL}
  access-key: minioadmin
  secret-key: minioadmin

platform:
  signature:
    keystore:
      path: classpath:certificate.p12
      password: ${KEYSTORE_PASSWORD}
      alias: Esign_App # (Thường là tên mặc định khi tạo chứng chỉ)

app:
  cron:
    # Ví dụ: Chạy vào lúc 00:00:00 mỗi ngày
    invitation-expiration-check: "0 0 7 * * *"