package com.spring.esign.enums;

public enum Notifications {
    DOCUMENT_RECEIVED, // KHI GUI TAI LIEU
    SIGNING_REMINDER, // NHAC NHO KI
    DOCUMENT_DECLINED, // KHI BI TU CHOI
    DOCUMENT_COMPLETED, // KHI HOAN THANH
    DOCUMENT_EXPIRED, // KHI HET HAN
    DOCUMENT_VOIDED; // KHI HUY TAI LIEU GUI DI
}
